### PR TITLE
Move scripts to npm scripts

### PR DESCRIPTION
**Pull request by szepeviktor**
- two less files
- one less technology (shell scripts)
- name npm scripts in `OBJECT:ACTION` format

### CODE REVIEW

**Comment by rosswintle** [comment]
Thanks.

Not all my projects use `npm`, so I like a more universal approach.

**Comment by szepeviktor** [comment]
All right.
This was an inspiration.

**Comment by szepeviktor** [comment]
> Not all my projects use `npm`

Really difficult to run `build.sh` as it calls `npm` 🤣

**Comment by rosswintle** [comment]
That's the point.

If I'm using `npm` then `build.sh` can call it.

If I'm _not_ using `npm` then `build.sh` can do whatever it needs to do instead.

**Comment by szepeviktor** [comment]
Old boys use/d `Makefile` to run commands, compile software.

Nowadays package managers have "scripts".

**Comment by rosswintle** [comment]
`Make` is probably a good alternative to my approach.

I might have a different package manager. Or I might have no package manager. I always have a shell!!

Keeping it simple and stack-independent! 👍

Thanks for the discussion.

**Pull request closed without merging**
